stages:
  - generate
  - build


generate:
  stage: generate
  image: python:3.10
  before_script:
    - pip install -r requirements.txt
  script:
    - copier copy --trust --defaults -d package_name=default                                    ros2_cpp_pkg packages
    - copier copy --trust --defaults -d package_name=component      -d is_component=true        ros2_cpp_pkg packages
    - copier copy --trust --defaults -d package_name=lifecycle      -d is_lifecycle=true        ros2_cpp_pkg packages
    - copier copy --trust --defaults -d package_name=service        -d has_service_server=true  ros2_cpp_pkg packages
    - copier copy --trust --defaults -d package_name=action         -d has_action_server=true   ros2_cpp_pkg packages
    - copier copy --trust --defaults -d package_name=timer          -d has_timer=true           ros2_cpp_pkg packages
    - copier copy --trust --defaults -d package_name=no_params      -d has_params:=false        ros2_cpp_pkg packages
    - copier copy --trust --defaults -d package_name=no_launch_file -d has_launch_file:=false   ros2_cpp_pkg packages
    - copier copy --trust --defaults -d package_name=all            -d is_component=true -d is_lifecycle=true -d has_service_server=true -d has_action_server=true -d has_timer=true ros2_cpp_pkg packages
  artifacts:
    paths:
      - packages/
    expire_in: 1 week


build:
  stage: build
  image: rwthika/ros2:latest
  script:
    - colcon build --continue-on-error
