stages:
  - generate
  - ros2_cpp_pkg
  - ros2_interfaces_pkg


generate:
  stage: generate
  image: python:3.10
  before_script:
    - pip install "copier~=9.1.1" "jinja2-strcase~=0.0.2"
    - git config --global user.name "dummy"
    - git config --global user.email "dummy@dummy.com"
  script:
    - copier copy --trust --defaults -d template=ros2_cpp_pkg         -d auto_shutdown=true -d package_name=pkg_default                                    . packages
    - copier copy --trust --defaults -d template=ros2_cpp_pkg         -d auto_shutdown=true -d package_name=pkg_component      -d is_component=true        . packages
    - copier copy --trust --defaults -d template=ros2_cpp_pkg         -d auto_shutdown=true -d package_name=pkg_lifecycle      -d is_lifecycle=true        . packages
    - copier copy --trust --defaults -d template=ros2_cpp_pkg         -d auto_shutdown=true -d package_name=pkg_service        -d has_service_server=true  . packages
    - copier copy --trust --defaults -d template=ros2_cpp_pkg         -d auto_shutdown=true -d package_name=pkg_action         -d has_action_server=true   . packages
    - copier copy --trust --defaults -d template=ros2_cpp_pkg         -d auto_shutdown=true -d package_name=pkg_timer          -d has_timer=true           . packages
    - copier copy --trust --defaults -d template=ros2_cpp_pkg         -d auto_shutdown=true -d package_name=pkg_no_params      -d has_params=false         . packages
    - copier copy --trust --defaults -d template=ros2_cpp_pkg         -d auto_shutdown=true -d package_name=pkg_no_launch_file -d has_launch_file=false    . packages
    - copier copy --trust --defaults -d template=ros2_cpp_pkg         -d auto_shutdown=true -d package_name=pkg_all            -d is_component=true -d is_lifecycle=true -d has_service_server=true -d has_action_server=true -d has_timer=true . packages
    - copier copy --trust --defaults -d template=ros2_interfaces_pkg  -d package_name=pkg_interfaces . packages
  artifacts:
    paths:
      - packages/
    expire_in: 1 week


.build:
  image: rwthika/ros2:latest

.build-ros2_cpp_pkg:
  extends: .build
  stage: ros2_cpp_pkg

.build-ros2_interfaces_pkg:
  extends: .build
  stage: ros2_interfaces_pkg

pkg_default:
  extends: .build-ros2_cpp_pkg
  script:
    - colcon build --packages-up-to pkg_default
    - source install/setup.bash
    - ros2 launch pkg_default pkg_default_launch.py

pkg_component:
  extends: .build-ros2_cpp_pkg
  script:
    - colcon build --packages-up-to pkg_component
    - source install/setup.bash
    - ros2 launch pkg_component pkg_component_launch.py

pkg_lifecycle:
  extends: .build-ros2_cpp_pkg
  script:
    - colcon build --packages-up-to pkg_lifecycle
    - source install/setup.bash
    - ros2 launch pkg_lifecycle pkg_lifecycle_launch.py

pkg_service:
  extends: .build-ros2_cpp_pkg
  script:
    - colcon build --packages-up-to pkg_service
    - source install/setup.bash
    - ros2 launch pkg_service pkg_service_launch.py

pkg_action:
  extends: .build-ros2_cpp_pkg
  script:
    - colcon build --packages-up-to pkg_action
    - source install/setup.bash
    - ros2 launch pkg_action pkg_action_launch.py

pkg_timer:
  extends: .build-ros2_cpp_pkg
  script:
    - colcon build --packages-up-to pkg_timer
    - source install/setup.bash
    - ros2 launch pkg_timer pkg_timer_launch.py

pkg_no_params:
  extends: .build-ros2_cpp_pkg
  script:
    - colcon build --packages-up-to pkg_no_params
    - source install/setup.bash
    - ros2 launch pkg_no_params pkg_no_params_launch.py

pkg_no_launch_file:
  extends: .build-ros2_cpp_pkg
  script:
    - colcon build --packages-up-to pkg_no_launch_file
    - source install/setup.bash
    - ros2 run pkg_no_launch_file pkg_no_launch_file --ros-args -p param:=1.0

pkg_all:
  extends: .build-ros2_cpp_pkg
  script:
    - colcon build --packages-up-to pkg_all
    - source install/setup.bash
    - ros2 launch pkg_all pkg_all_launch.py

pkg_interfaces:
  extends: .build-ros2_interfaces_pkg
  script:
    - colcon build --packages-up-to pkg_interfaces
    - ros2 interface show pkg_interfaces/msg/Message
    - ros2 interface show pkg_interfaces/srv/Service
    - ros2 interface show pkg_interfaces/action/Action
