stages:
  - generate
  - build


generate:
  stage: generate
  image: python:3.10
  before_script:
    - pip install "copier~=8.3.0" "jinja2-strcase~=0.0.2"
    - git config --global user.name "dummy"
    - git config --global user.email "dummy@dummy.com"
  script:
    - copier copy --trust --defaults -d template=ros2_cpp_pkg -d package_name=pkg_default                                    . packages
    - copier copy --trust --defaults -d template=ros2_cpp_pkg -d package_name=pkg_component      -d is_component=true        . packages
    - copier copy --trust --defaults -d template=ros2_cpp_pkg -d package_name=pkg_lifecycle      -d is_lifecycle=true        . packages
    - copier copy --trust --defaults -d template=ros2_cpp_pkg -d package_name=pkg_service        -d has_service_server=true  . packages
    - copier copy --trust --defaults -d template=ros2_cpp_pkg -d package_name=pkg_action         -d has_action_server=true   . packages
    - copier copy --trust --defaults -d template=ros2_cpp_pkg -d package_name=pkg_timer          -d has_timer=true           . packages
    - copier copy --trust --defaults -d template=ros2_cpp_pkg -d package_name=pkg_no_params      -d has_params=false         . packages
    - copier copy --trust --defaults -d template=ros2_cpp_pkg -d package_name=pkg_no_launch_file -d has_launch_file=false    . packages
    - copier copy --trust --defaults -d template=ros2_cpp_pkg -d package_name=pkg_all            -d is_component=true -d is_lifecycle=true -d has_service_server=true -d has_action_server=true -d has_timer=true . packages
  artifacts:
    paths:
      - packages/
    expire_in: 1 week


.build:
  stage: build
  image: rwthika/ros2:latest

pkg_default:
  extends: .build
  script:
    - colcon build --packages-up-to pkg_default

pkg_component:
  extends: .build
  script:
    - colcon build --packages-up-to pkg_component

pkg_lifecycle:
  extends: .build
  script:
    - colcon build --packages-up-to pkg_lifecycle

pkg_service:
  extends: .build
  script:
    - colcon build --packages-up-to pkg_service

pkg_action:
  extends: .build
  script:
    - colcon build --packages-up-to pkg_action

pkg_timer:
  extends: .build
  script:
    - colcon build --packages-up-to pkg_timer

pkg_no_params:
  extends: .build
  script:
    - colcon build --packages-up-to pkg_no_params

pkg_no_launch_file:
  extends: .build
  script:
    - colcon build --packages-up-to pkg_no_launch_file

pkg_all:
  extends: .build
  script:
    - colcon build --packages-up-to pkg_all
