stages:
  - generate
  - build


generate:
  stage: generate
  image: python:3.10
  before_script:
    - pip install -r requirements.txt
  script:
    - copier copy --trust -d package_name=pkg --defaults ros2_cpp_pkg packages
    - copier copy --trust -d package_name=component_pkg -d is_component=true --defaults ros2_cpp_pkg packages
    - copier copy --trust -d package_name=action_pkg -d has_action_server=true --defaults ros2_cpp_pkg packages
  artifacts:
    paths:
      - packages/
    expire_in: 1 week


build:
  stage: build
  image: rwthika/ros2:latest
  script:
    - colcon build --continue-on-error
