stages:
  - generate
  - build


generate:
  stage: generate
  image: python:3.10
  before_script:
    - pip install "copier~=8.3.0" "jinja2-strcase~=0.0.2"
    - git config --global user.name "dummy"
    - git config --global user.email "dummy@dummy.com"
  script:
    - copier copy --trust --defaults -d auto_shutdown=true -d template=ros2_cpp_pkg -d package_name=pkg_default                                    . packages
    - copier copy --trust --defaults -d auto_shutdown=true -d template=ros2_cpp_pkg -d package_name=pkg_component      -d is_component=true        . packages
    - copier copy --trust --defaults -d auto_shutdown=true -d template=ros2_cpp_pkg -d package_name=pkg_lifecycle      -d is_lifecycle=true        . packages
    - copier copy --trust --defaults -d auto_shutdown=true -d template=ros2_cpp_pkg -d package_name=pkg_service        -d has_service_server=true  . packages
    - copier copy --trust --defaults -d auto_shutdown=true -d template=ros2_cpp_pkg -d package_name=pkg_action         -d has_action_server=true   . packages
    - copier copy --trust --defaults -d auto_shutdown=true -d template=ros2_cpp_pkg -d package_name=pkg_timer          -d has_timer=true           . packages
    - copier copy --trust --defaults -d auto_shutdown=true -d template=ros2_cpp_pkg -d package_name=pkg_no_params      -d has_params=false         . packages
    - copier copy --trust --defaults -d auto_shutdown=true -d template=ros2_cpp_pkg -d package_name=pkg_no_launch_file -d has_launch_file=false    . packages
    - copier copy --trust --defaults -d auto_shutdown=true -d template=ros2_cpp_pkg -d package_name=pkg_all            -d is_component=true -d is_lifecycle=true -d has_service_server=true -d has_action_server=true -d has_timer=true . packages
  artifacts:
    paths:
      - packages/
    expire_in: 1 week


.build:
  stage: build
  image: rwthika/ros2:latest

pkg_default:
  extends: .build
  script:
    - colcon build --packages-up-to pkg_default
    - ros2 launch pkg_default pkg_default.launch.xml

pkg_component:
  extends: .build
  script:
    - colcon build --packages-up-to pkg_component
    - ros2 launch pkg_component pkg_component.launch.xml

pkg_lifecycle:
  extends: .build
  script:
    - colcon build --packages-up-to pkg_lifecycle
    - ros2 launch pkg_lifecycle pkg_lifecycle.launch.xml

pkg_service:
  extends: .build
  script:
    - colcon build --packages-up-to pkg_service
    - ros2 launch pkg_service pkg_service.launch.xml

pkg_action:
  extends: .build
  script:
    - colcon build --packages-up-to pkg_action
    - ros2 launch pkg_action pkg_action.launch.xml

pkg_timer:
  extends: .build
  script:
    - colcon build --packages-up-to pkg_timer
    - ros2 launch pkg_timer pkg_timer.launch.xml

pkg_no_params:
  extends: .build
  script:
    - colcon build --packages-up-to pkg_no_params
    - ros2 launch pkg_no_params pkg_no_params.launch.xml

pkg_no_launch_file:
  extends: .build
  script:
    - colcon build --packages-up-to pkg_no_launch_file
    - ros2 run pkg_no_launch_file pkg_no_launch_file --ros-args -p param:=1.0

pkg_all:
  extends: .build
  script:
    - colcon build --packages-up-to pkg_all
    - ros2 launch pkg_all pkg_all.launch.xml
